name: PR Build, Merge, and Deploy
on:
  pull_request:
    branches:
      - main
jobs:
  build-merge-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.19.0'
    - name: Install dependencies
      run: npm install
    - name: Build Next.js project
      run: npm run build
    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
          browser: chrome
          build: npm run build
          start: npm start
    - name: Merge PR if checks pass
      run: |
        if [ “${{ github.event_name }}” == “pull_request” ] && [ “${{ github.event.action }}” == “opened” ]; then
          gh pr merge “${{ github.event.number }}” --squash --auto
        fi
    - name: Deploy to Vercel
      run: npx vercel --token ${{ secrets.TEST }}
