name: PR Build, Merge, and Deploy
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    branches:
      - main
jobs:
  build-merge-deploy:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.19.0'
    - name: Install dependencies
      run: npm install

    - name: Setup Supabase Cli
      uses: supabase/setup-cli@v1

    - name: Run Test
      run: npm run test:local

    - name: Build Next.js project
      run: npm run build
    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
          browser: chrome
          build: npm run build
          start: npm start
    - name: Merge PR if checks pass
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.event.action }}" == "opened" ]; then
          gh pr merge "${{ github.event.number }}" --squash --auto
        fi
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=preview --token=${{ secrets.TEST }}
    - name: Build Project Artifacts
      run: vercel build --token=${{ secrets.TEST }}
    - name: Deploy Project Artifacts to Vercel
      run: vercel deploy --prebuilt --token=${{ secrets.TEST }}